### ISSUE TITLE
I am unable to load maya generated .dae files

### ISSUE THREAD

**Issue by sivaprasadnamburu** [zidarsk8/galaxyCar#1]
getting null pointer exception while loading dae files. Could you please look into this issue and provide me the solution.

Thanks in advance

**Comment by zidarsk8** [comment]
Hey, Sorry But I haven't touched this code in such a long time that I don't think I can help you now.

When we were doing this, we only used it with .obj files exported with blender. Even obj files from google sketchup had issues. If you Really wish to use this project, try importing .obj file to blender and export the .obj from there.

PS: this is code from a bunch of students learning and doing everything wrong, don't put too much faith in it.
